
<MenuWidget>:
    canvas.before:
        Color:
            rgba: (.5, .8, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
    Label:
        text: "Sudoku App"
        pos_hint: { "center_x": .5, "center_y": .6}
    Button:
        text: "Sudoku"
        pos_hint: { "center_x": .5, "center_y": .4}
        size_hint: .5, .05
        canvas.before:
	        Rectangle:
	          #  color: (1, 0, 0, 1)
	            size: self.size
	            pos: self.pos
	           # radius: (30, 15, 15, 15)
        on_press: root.manager.current = "puzzle"