#:import menu menu

MainWidget:

<MainWidget>:
    MainBoxLayout

<MainBoxLayout>:
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: (.95, .95, .95, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<UpperBoxLayout>:
    orientation: "vertical"
    size_hint: 1, .12
    #height: 32
    canvas.before:
        Color:
            rgba: (.5, .8, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos
    Button:
        background_color: (1, 1, 1, .25) if self.state == "normal" else (1, 1, 1, .15)
        background_normal: "images/burger_icon.webp"
        background_down: "images/burger_icon.webp"
        pos_hint: {"x": 0.01}
        size_hint: (0.15, .9)
        #size: "64dp", "64dp"
        on_press: root.parent.parent.manager.current = "menu"

<Cell>:
    background_color: 0, 0, 0, 0
    background_normal: ""
    bold: "True"
    group: "Cells"
    font_size: self.size[0] * .8
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1) if self.state == "normal" else (.5, .8, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<NumPadCornerButton1>:
    background_color: 0, 0, 0, 0
    background_normal: ''
    bold: "True"
    font_size: self.size[0] * .6
    color: (.4, .4, .4, 1)
    canvas.before:
        Color:
            rgba: (.8, .8, .8, 1) if self.state == "normal" else (.5, .8, 1, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: (6, 0, 0, 0)

<NumPadCornerButton2>:
    background_color: 0, 0, 0, 0
    background_normal: ''
    bold: "True"
    font_size: self.size[0] * .6
    color: (.4, .4, .4, 1)
    canvas.before:
        Color:
            rgba: (.8, .8, .8, 1) if self.state == "normal" else (.5, .8, 1, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: (0, 6, 0, 0)

<NumPadCornerButton3>:
    background_color: 0, 0, 0, 0
    background_normal: ''
    bold: "True"
    font_size: self.size[0] * .3
    color: (.4, .4, .4, 1)
    canvas.before:
        Color:
            rgba: (.8, .8, .8, 1) if self.state == "normal" else (.5, .8, 1, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: (0, 0, 0, 6)

<NumPadCornerButton4>:
    background_color: 0, 0, 0, 0
    background_normal: ''
    bold: "True"
    font_size: self.size[0] * .3
    color: (.4, .4, .4, 1)
    canvas.before:
        Color:
            rgba: (.8, .8, .8, 1) if self.state == "normal" else (.5, .8, 1, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: (0, 0, 6, 0)

<NumPadButton>:
    background_color: 0, 0, 0, 0
    background_normal: ''
    bold: "True"
    font_size: self.size[0] * .6
    color: (.4, .4, .4, 1)
    canvas.before:
        Color:
            rgba: (.8, .8, .8, 1) if self.state == "normal" else (.5, .8, 1, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<NumPadLayout>:
    size_hint: None, None
    size: "220dp", "280dp"
    pos_hint: {"center_x": .53}
    padding: [16]
    spacing: [6, 6]
    canvas.before:
        Color:
            rgba: (.95, .95, .95, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<SudokuBox>:
    rows: 3
    spacing: [4, 4]
    canvas.before:
        Color:
            rgba: (0.7, 0.7, 0.7, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<SudokuGrid>:
    size_hint: .9, None
    height: self.size[0]
    pos_hint: {"center_x": .5, "center_y": .5}
    rows: 3
    padding: [6]
    spacing: [6, 6]
    canvas.before:
        Color:
            rgba: (0, 0, 0, 1)
        Rectangle:
            size: self.size
            pos: self.pos

<SudokuGridLayout>:
    SudokuGrid